= asciidoctor-lifecycle-maven-plugin
//
:release-version: 1.0-SNAPSHOT
:idprefix:
:idseparator: -
//
ifdef::env-github,env-browser[]
:toc: preamble
endif::[]
//
ifndef::env-github[:icons: font]
//
:project-repo: asciidoctor-lifecycle-maven-plugin/asciidoctor-lifecycle-maven-plugin
:uri-repo: https://github.com/{project-repo}
:uri-asciidoc: http://asciidoc.org
:uri-asciidoctor: http://asciidoctor.org
:uri-examples: https://github.com/asciidoctor-lifecycle-maven-plugin/asciidoctor-lifecycle-maven-plugin-examples
:uri-maven: http://maven.apache.org
ifdef::env-github[]
:!toc-title:
:badges:
:tag: master
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Badges
ifdef::badges[]
image:https://travis-ci.com/{project-repo}.svg?branch=master[Build status (Travis CI)",link="https://travis-ci.com/asciidoctor-lifecycle-maven-plugin/asciidoctor-lifecycle-maven-plugin"]
image:https://www.codefactor.io/repository/github/asciidoctor-lifecycle-maven-plugin/asciidoctor-lifecycle-maven-plugin/badge[CodeFactor, link="https://www.codefactor.io/repository/github/asciidoctor-lifecycle-maven-plugin/asciidoctor-lifecycle-maven-plugin"]
image:https://api.codacy.com/project/badge/Grade/f01251c7d205471d87060224bf354b66[Codacy,link="https://app.codacy.com/app/asciidoctor-lifecycle-maven-plugin/asciidoctor-lifecycle-maven-plugin"]
endif::[]

A lifecycle and custom mojos to isolate the building of asciidoctor
documentation from the default lifecycle with the asciidoctor-maven-plugin.

== About this project

=== Last changes

In this section I will tell you the most recent changes.
This section will disappear with the final release.

.2019/08/18
* Renamed the `theme-download` phase to `theme` phase, because in this phase
we do other things, as unzip and create properties, and the download is done only
if the artifact is not in the local repository.
* Renamed the `pre-build` phase to `prepare-build`.
* Renamed the `pre-upload` phase to `prepare-upload`.
* Added a basic support for the `upload` phase, the UploadMojo.
* The property names are refactorized.
* Added the Maven site (basic).
* Documentation updated.

.2019/08/16
* In the `theme` phase for each downloaded theme,
  a property is created. Its value is the path where it was unzipped.
* Documentation updated.

=== What this project offers?

This project offers a new Maven plugin, with the following functionalities (this is a work in progress):

* A new lifecycle, designed for resolving some of the needs I've found in my personal projects.
* A mojo for downloading themes for using with Asciidoctor Maven Plugin.

I hope this plugin helps others to write a cleaner separation between the build of the asciidoc documentation 

=== Why this project?

This project tries to cover those aspects of asciidoctor-maven-plugin that doesn't fit well with the Maven default lifecycle.
What are this aspects?

* When a project contains asciidoc documentation and code, you need a complicated configuration to build only asciidoc or only code.
Profiles here may be a solution, specifying modules to build in every one, but...
* The default lifecycle seems oriented to code building;
this is not something negative in itself, 
but the name of the phases are confusing enough if we think about documentation and not code (`compile`, `test`, `verify`).
* If you want to build the site documentation, Maven offers you another lifecycle, the *site* lifecycle.
* If you need to download a theme for generating a pdf (for example) you need to use the `dependency:get` as a solution,
and if you need to do something more with the theme content may be you more and more configuration.

So, why not develop a custom lifecycle?

== Status of this project

This project is a Work In Progress, in early stage of development.
You can test it or use it at your own projects, but you should understand:

. Something can change at any time before the first release, breaking compatibility with pre releases versions.
. There is no version available in any repository yet.
. You have to build it with your own hands (it is not difficult, it is a standard Maven project).

== A custom lifecycle for build Asciidoctor projects

=== The lifecycle asciidoctor-lifecycle-build

This lifecycle add a defined sequence of phases that helps to build the Asciidoctor documents
without the use of profiles. These are the phases of this lifecycle (in sequential order):

[%header%autowidth.spread,cols="h,,"]
|===
|Phase          |Description |Mojo   
//----------------------
|theme          |In this phase the themes are downloaded from remote repositories,
if required, and then unzipped. | ThemeDownloadMojo
|prepare-build  |Actions to be performed before the build.
Copy the theme to another location, modify it contents...|
|build          |The `process-asciidoc` should be attached to this phase, to build the documentation|
|prepare-upload |Actions to be performed before the upload phase|
|upload         |Actions to be performed for uploading the generated content|
|notice         |Actions to be performed for notifying users the new documentation version|
|===

You will notice that the `asciidoctor-lifecycle@build` goal is not bound by default to the `asciidoctor@process-asciidoc` goal.

The main reason is that if you define a shared configuration and several executions,
an additional document corresponding to the default backend (dockbook) will be generated.
This is by design of the `asciidoctor-maven-plugin`.

== Themes
=== What is a theme?

For the moment a theme in asciidoctor-lifecycle is only an artifact wich zip packaging.
This requirement allow us uncompress its contents to a folder.

At the moment it has not been formally defined or its contents established.

=== How Asciidoctor Lifecycle Maven Plugin manages themes

You can define the use of a theme (downloading and unpacking it to a directory) as part of the
`asciidoctor-lifecycle-maven-plugin` configuration.
You can configure so many themes as you desire.

The themes are expressed as Maven coordinates as:

[.text-center]
`<groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>`

So a valid theme expression is:

[.text-center]
`groupId:artifactId:zip:3.3.3`

The Asciidoctor Lifecycle Maven Pluging does the following operations for every configured theme:

. Tries to download the artifact (theme).
. Tries to unzip the contents of the artifact downloaded to a directory,
specified by the configuration property `themesBaseDir` as parent directory,
and the directory child name is the same as its `artifactId`.
. Creates a property with the value of the path of the directory where the theme
was unzipped.
. If any of the previous operations fails, it breaks the build.

All these operations are done at `theme` phase, so using the Asciidoctor Lifecycle
you can use  in the rest of the phases the property created automatically at this phase.

== How to use the lifecycle

=== Configure the new lifecycle in pom.xml

It is very easy use this new lifecycle.
It is a standard Maven plugin.

[source,xml]
----
<plugin>
    <groupId>com.coutemeier.maven.plugins</groupId>
    <artifactId>asciidoctor-lifecycle-maven-plugin</artifactId>
    <version>1.0-SNAPSHOT</version>
    <extensions>true</extensions> <!--1-->
</plugin>
----
<1> We use the plugin as an extension.

=== Configure the asciidoctor-maven-plugin

We configure the
https://github.com/asciidoctor/asciidoctor-maven-plugin/[asciidoctor-maven-plugin]
attaching the `process-asciidoc` goal to the `build` phase.


[source,xml]
----
<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>1.5.8</version>
    <executions>
    <!-- So many executions as you need -->
        <execution>
            <id>output-html</id>              
            <phase>build</phase> <!--1-->
            <goals>
                <goal>process-asciidoc</goal> 
            </goals>
            <configuration>
                <backend>html5</backend>
            </configuration>
        </execution>
    </executions>
</plugin>
----

<1> We attach the `asciidoctor-maven-plugin:process-asciidoc` goal 
to the build phase of the `asciidoctor-lifecycle-build` lifecycle.

We are ready to generate our documentation separate of the normal build of our code.

=== Generate the html documents

[source,shell]
mvn build

== Some examples explained in detail

=== How to use the automatically created properties

Suposse you configure the `asciidoctor-maven-plugin` and the `asciidoctor-lifecycle-maven-plugin`
as (I show you only the relevant configuration for this purpose):

[source,xml]
----
<plugin>
    <groupId>com.coutemeier.maven.plugins</groupId>
    <artifactId>asciidoctor-lifecycle-maven-plugin</artifactId>
    <version>1.0-SNAPSHOT</version>
    <extensions>true</extensions>
    <configuration>
        <themesBaseDir>${project.build.directory}/asciidoctor-themes</themesBaseDir> <!--1-->
        <themes>
            <theme>com.coutemeier.maven.plugins:theme-example-1:zip:1.2.0</theme> <!--2-->
            <theme>com.coutemeier.maven.plugins:theme-example-2:zip:2.2.1</theme>
        </themes>
    </configuration>
</plugin>

<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>${asciidoctor.maven.plugin.version}</version>
    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>${asciidoctorj.pdf.version}</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <id>generate-pdf-doc-custom-theme</id>
            <phase>build</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>pdf</backend>
                <outputDirectory>${project.build.directory}/generated-docs-custom-theme</outputDirectory>
                <sourceHighlighter>coderay</sourceHighlighter>
                <doctype>book</doctype>
                <attributes>
                    <!-- 
                        The property "asciidoctor.theme.theme-example-1.path" is created at `theme` phase,
                        so it is not needed to define it in the pom.xml.
                    -->
                    <pdf-stylesdir>${asciidoctor.theme.theme-example-1.path}/pdf</pdf-stylesdir> <!--3-->
                    <pdf-style>custom</pdf-style>
                    <icons>font</icons>
                    <pagenums/>
                    <toc/>
                    <idprefix/>
                    <idseparator>-</idseparator>
                </attributes>
            </configuration>
        </execution>
    </executions>
</plugin>
----

<1> The directory where themes will be unzipped (this is the default value).
<2> You need the plugin whose coordinates are `com.coutemeier.maven.plugins:theme-example-1:zip:1.2.0`. 
<3> You configure the path of the theme using the property `asciidoctor.theme.theme-example-1.path`,
created at `theme` phase.

After the `theme` phase execution you'll get:

. Two directories in the `target/asciidoctor-themes`:
  * `theme-example-1`
  * `theme-example-2`
. Two properties are created in this phase, so you can use them in later phases.
  * `asciidoctor.theme.theme-example-1.path = ${project.output.dir}/asciidoctor-themes/theme-example1`
  * `asciidoctor.theme.theme-example-2.path = ${project.output.dir}/asciidoctor-themes/theme-example2`

In the `build` phase execution:

. The property `asciidoctor.theme.theme-example-1.path` and `asciidoctor.theme.theme-example-2.path` are defined,
so you can use them as a property to configure the path of the YAML file.

== How can I build the plugin?

You can build the project with Maven 3.5.0 and Java 8.

[source,shell]
mvn clean package

You can launch the integration tests:

[source,shell]
mvn integration-test -Prun-it

== References

* https://asciidoctor.org/[Asciidoctor home page]
* https://github.com/asciidoctor/asciidoctor-maven-plugin[asciidoctor-maven-plugin in Github]